import type { IncentiveOffer, SourceStatus, VehicleModel } from './types';

export const vehicleModels: VehicleModel[] = [
  {
    id: 'toyota-camry-se-2026',
    year: 2026,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE Hybrid',
    bodyStyle: 'sedan',
    fuelType: 'hybrid',
    msrp: 31750,
    sourceIds: { vpic: 'toyota-camry', fueleconomy: 'camry-hybrid' },
  },
  {
    id: 'ford-maverick-xlt-2026',
    year: 2026,
    make: 'Ford',
    model: 'Maverick',
    trim: 'XLT',
    bodyStyle: 'truck',
    fuelType: 'hybrid',
    msrp: 30240,
    sourceIds: { vpic: 'ford-maverick', fueleconomy: 'maverick-hybrid' },
  },
  {
    id: 'hyundai-ioniq5-sel-2026',
    year: 2026,
    make: 'Hyundai',
    model: 'Ioniq 5',
    trim: 'SEL',
    bodyStyle: 'suv',
    fuelType: 'electric',
    msrp: 48750,
    sourceIds: { vpic: 'hyundai-ioniq-5', fueleconomy: 'ioniq-5' },
  },
  {
    id: 'toyota-rav4-xle-2026',
    year: 2026,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'XLE',
    bodyStyle: 'suv',
    fuelType: 'gas',
    msrp: 34225,
    sourceIds: { vpic: 'toyota-rav4', fueleconomy: 'rav4' },
  },
  {
    id: 'ford-escape-active-2026',
    year: 2026,
    make: 'Ford',
    model: 'Escape',
    trim: 'Active',
    bodyStyle: 'suv',
    fuelType: 'gas',
    msrp: 32110,
    sourceIds: { vpic: 'ford-escape', fueleconomy: 'escape' },
  },
  {
    id: 'hyundai-elantra-sel-2026',
    year: 2026,
    make: 'Hyundai',
    model: 'Elantra',
    trim: 'SEL Sport',
    bodyStyle: 'sedan',
    fuelType: 'gas',
    msrp: 24780,
    sourceIds: { vpic: 'hyundai-elantra', fueleconomy: 'elantra' },
  },
];

export const incentiveOffers: IncentiveOffer[] = [
  {
    id: 'offer-camry-philly',
    vehicleId: 'toyota-camry-se-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance', 'rebate'],
    cashAmount: 1250,
    aprPercent: 3.99,
    financeTermMonths: 48,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-07-08',
    eligibility: ['Qualified buyers', 'Regional dealer participation may vary'],
    sourceUrl: 'https://www.toyota.com/deals-incentives/',
    sourceName: 'Toyota public offers',
    fetchedAt: '2026-06-27T14:30:00-04:00',
    parserConfidence: 'medium',
    coverageNote: 'Public offer copy was normalized from Toyota regional incentives.',
  },
  {
    id: 'offer-maverick-philly',
    vehicleId: 'ford-maverick-xlt-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance', 'rebate'],
    cashAmount: 750,
    aprPercent: 2.9,
    financeTermMonths: 60,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-07-31',
    eligibility: ['Qualified buyers through captive finance', 'Inventory dependent'],
    sourceUrl: 'https://www.ford.com/incentives/',
    sourceName: 'Ford public offers',
    fetchedAt: '2026-06-27T14:25:00-04:00',
    parserConfidence: 'medium',
    coverageNote: 'Public offer availability should be rechecked by ZIP before purchase.',
  },
  {
    id: 'offer-ioniq5-philly',
    vehicleId: 'hyundai-ioniq5-sel-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['lease', 'rebate'],
    cashAmount: 7500,
    aprPercent: null,
    financeTermMonths: null,
    leaseMonthly: 329,
    leaseDueAtSigning: 3999,
    leaseTermMonths: 36,
    expiresAt: '2026-07-01',
    eligibility: ['Lease cash may require captive finance', 'Federal clean vehicle rules are not assumed current'],
    sourceUrl: 'https://www.hyundaiusa.com/us/en/offers',
    sourceName: 'Hyundai public offers',
    fetchedAt: '2026-06-27T14:20:00-04:00',
    parserConfidence: 'low',
    coverageNote: 'Lease cash is public-source observed and requires dealer confirmation.',
  },
  {
    id: 'offer-rav4-philly',
    vehicleId: 'toyota-rav4-xle-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance'],
    cashAmount: 0,
    aprPercent: 4.49,
    financeTermMonths: 48,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-07-08',
    eligibility: ['Qualified buyers', 'Trim exclusions may apply'],
    sourceUrl: 'https://www.toyota.com/deals-incentives/',
    sourceName: 'Toyota public offers',
    fetchedAt: '2026-06-27T14:18:00-04:00',
    parserConfidence: 'medium',
    coverageNote: 'Finance terms verified; cash rebate not verified for this trim.',
  },
  {
    id: 'offer-escape-philly',
    vehicleId: 'ford-escape-active-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['lease', 'rebate'],
    cashAmount: 1750,
    aprPercent: null,
    financeTermMonths: null,
    leaseMonthly: 389,
    leaseDueAtSigning: 3149,
    leaseTermMonths: 39,
    expiresAt: '2026-07-31',
    eligibility: ['Lease acquisition fee not included', 'Taxes and dealer fees vary'],
    sourceUrl: 'https://www.ford.com/incentives/',
    sourceName: 'Ford public offers',
    fetchedAt: '2026-06-27T14:12:00-04:00',
    parserConfidence: 'medium',
    coverageNote: 'Public lease offer parsed with due-at-signing normalized into effective monthly cost.',
  },
  {
    id: 'offer-elantra-philly',
    vehicleId: 'hyundai-elantra-sel-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance', 'lease', 'rebate'],
    cashAmount: 1000,
    aprPercent: 3.49,
    financeTermMonths: 60,
    leaseMonthly: 249,
    leaseDueAtSigning: 2999,
    leaseTermMonths: 36,
    expiresAt: '2026-07-01',
    eligibility: ['Qualified lessees', 'Dealer contribution may be required'],
    sourceUrl: 'https://www.hyundaiusa.com/us/en/offers',
    sourceName: 'Hyundai public offers',
    fetchedAt: '2026-06-27T14:10:00-04:00',
    parserConfidence: 'high',
    coverageNote: 'Finance, lease, and cash values were all present in the fixture snapshot.',
  },
];

export const sourceStatuses: SourceStatus[] = [
  {
    id: 'nhtsa-vpic',
    name: 'NHTSA vPIC',
    category: 'model-catalog',
    status: 'fixture-backed',
    coverage: 'Used to normalize make/model/year identity; not an incentive source.',
    lastChecked: '2026-06-27',
    url: 'https://vpic.nhtsa.dot.gov/api/',
  },
  {
    id: 'fueleconomy-gov',
    name: 'FuelEconomy.gov',
    category: 'model-catalog',
    status: 'fixture-backed',
    coverage: 'Used for fuel type support and future EV/hybrid normalization.',
    lastChecked: '2026-06-27',
    url: 'https://www.fueleconomy.gov/feg/ws/',
  },
  {
    id: 'toyota-public-offers',
    name: 'Toyota public offers',
    category: 'oem-offer',
    status: 'fixture-backed',
    coverage: 'Proof adapter target for public regional cash and APR offers.',
    lastChecked: '2026-06-27',
    url: 'https://www.toyota.com/deals-incentives/',
  },
  {
    id: 'ford-public-offers',
    name: 'Ford public offers',
    category: 'oem-offer',
    status: 'fixture-backed',
    coverage: 'Proof adapter target for public APR, lease, and retail bonus offers.',
    lastChecked: '2026-06-27',
    url: 'https://www.ford.com/incentives/',
  },
  {
    id: 'hyundai-public-offers',
    name: 'Hyundai public offers',
    category: 'oem-offer',
    status: 'fixture-backed',
    coverage: 'Proof adapter target for public lease, finance, and rebate pages.',
    lastChecked: '2026-06-27',
    url: 'https://www.hyundaiusa.com/us/en/offers',
  },
  {
    id: 'irs-clean-vehicle',
    name: 'IRS clean vehicle credit',
    category: 'tax-credit',
    status: 'historical',
    coverage: 'Shown as historical until current law/source checks prove eligibility for today.',
    lastChecked: '2026-06-27',
    url: 'https://www.irs.gov/credits-deductions/clean-vehicle-credit-seller-or-dealer-requirements',
  },
];
