import type { IncentiveOffer, SourceStatus, VehicleModel } from './types';

const checkedAt = '2026-09-28T12:06:00-04:00';
const checkedDate = '2026-09-28';

export const vehicleModels: VehicleModel[] = [
  {
    id: 'toyota-camry-se-2026',
    year: 2026,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE Hybrid',
    bodyStyle: 'sedan',
    fuelType: 'hybrid',
    msrp: 31750,
    sourceIds: { vpic: 'toyota-camry', fueleconomy: 'camry-hybrid' },
  },
  {
    id: 'ford-maverick-xlt-2026',
    year: 2026,
    make: 'Ford',
    model: 'Maverick',
    trim: 'XLT',
    bodyStyle: 'truck',
    fuelType: 'hybrid',
    msrp: 30240,
    sourceIds: { vpic: 'ford-maverick', fueleconomy: 'maverick-hybrid' },
  },
  {
    id: 'hyundai-ioniq5-sel-2026',
    year: 2026,
    make: 'Hyundai',
    model: 'Ioniq 5',
    trim: 'SEL RWD',
    bodyStyle: 'suv',
    fuelType: 'electric',
    msrp: 48750,
    sourceIds: { vpic: 'hyundai-ioniq-5', fueleconomy: 'ioniq-5' },
  },
  {
    id: 'toyota-rav4-xle-2026',
    year: 2026,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'XLE',
    bodyStyle: 'suv',
    fuelType: 'gas',
    msrp: 34225,
    sourceIds: { vpic: 'toyota-rav4', fueleconomy: 'rav4' },
  },
  {
    id: 'ford-escape-active-2026',
    year: 2026,
    make: 'Ford',
    model: 'Escape',
    trim: 'Active',
    bodyStyle: 'suv',
    fuelType: 'gas',
    msrp: 32110,
    sourceIds: { vpic: 'ford-escape', fueleconomy: 'escape' },
  },
  {
    id: 'hyundai-elantra-sel-2026',
    year: 2026,
    make: 'Hyundai',
    model: 'Elantra',
    trim: 'SEL Sport FWD',
    bodyStyle: 'sedan',
    fuelType: 'gas',
    msrp: 24780,
    sourceIds: { vpic: 'hyundai-elantra', fueleconomy: 'elantra' },
  },
];

// This is a dated public-page snapshot, not a live ZIP/inventory quote.
export const incentiveOffers: IncentiveOffer[] = [
  {
    id: 'offer-camry-apr-philly-202609',
    vehicleId: 'toyota-camry-se-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance'],
    cashAmount: 0,
    aprPercent: 4.49,
    financeTermMonths: 48,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-09-30',
    eligibility: ['Qualified customers through Toyota Financial Services', 'Only very well-qualified customers', 'Cannot be combined with lease, lease subvention cash, customer cash, trade-in assistance, or down-payment assistance'],
    sourceUrl: 'https://www.toyota.com/centralatlantic/deals-incentives/camry_apr_251d47f1-0614-41d9-ad31-9a8bd7c51bae/?vehicles=camry',
    sourceName: 'Toyota public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'high',
    coverageNote: 'Central Atlantic Toyota lists 4.49% APR for 48 months on the 2026 Camry, including the SE Hybrid. Approval and dealer terms apply.',
  },
  {
    id: 'offer-camry-lease-philly-202609',
    vehicleId: 'toyota-camry-se-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['lease'],
    cashAmount: 0,
    aprPercent: null,
    financeTermMonths: null,
    leaseMonthly: 319,
    leaseDueAtSigning: 3999,
    leaseTermMonths: 36,
    expiresAt: '2026-09-30',
    eligibility: ['2026 Camry SE Hybrid', '10,000 miles per year', 'Qualified lessees; taxes, title, registration, dealer options, and charges excluded'],
    sourceUrl: 'https://www.toyota.com/centralatlantic/deals-incentives/',
    sourceName: 'Toyota public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'high',
    coverageNote: 'Central Atlantic Toyota lists $319 per month for 36 months with $3,999 due at signing for the 2026 Camry SE Hybrid. Confirm local inventory and final fees.',
  },
  {
    id: 'offer-ioniq5-apr-philly-202609',
    vehicleId: 'hyundai-ioniq5-sel-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance'],
    cashAmount: 0,
    aprPercent: 0.9,
    financeTermMonths: 60,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-09-30',
    eligibility: ['Hyundai lists this APR for all 2026 IONIQ 5 trims', 'Qualified buyers and Hyundai Motor Finance approval required', 'Do not assume it can be combined with advertised total-savings offers'],
    sourceUrl: 'https://www.hyundaiusa.com/us/en/offers',
    sourceName: 'Hyundai public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'medium',
    coverageNote: 'Hyundai currently advertises 0.9% APR for up to 60 months on the 2026 IONIQ 5. The page also advertises total savings, but does not establish that those savings combine with this APR.',
  },
  {
    id: 'offer-ioniq5-lease-philly-202609',
    vehicleId: 'hyundai-ioniq5-sel-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['lease'],
    cashAmount: 0,
    aprPercent: null,
    financeTermMonths: null,
    leaseMonthly: 389,
    leaseDueAtSigning: 4999,
    leaseTermMonths: 24,
    expiresAt: '2026-09-30',
    eligibility: ['2026 IONIQ 5 SEL RWD', 'Qualified lessees and Hyundai Motor Finance approval required', 'Taxes, fees, mileage allowance, and local dealer availability require confirmation'],
    sourceUrl: 'https://www.hyundaiusa.com/us/en/offers',
    sourceName: 'Hyundai public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'medium',
    coverageNote: 'Hyundai lists $389 per month for 24 months with $4,999 due at signing for the 2026 IONIQ 5 SEL RWD. Confirm local terms and mileage allowance with a dealer.',
  },
  {
    id: 'offer-rav4-apr-philly-202609',
    vehicleId: 'toyota-rav4-xle-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['finance'],
    cashAmount: 0,
    aprPercent: 4.99,
    financeTermMonths: 48,
    leaseMonthly: null,
    leaseDueAtSigning: null,
    leaseTermMonths: null,
    expiresAt: '2026-09-30',
    eligibility: ['Applies to 9 trims, including XLE', 'Through Toyota Financial Services for only very well-qualified buyers', 'Cannot be combined with lease cash, customer cash, trade-in assistance, or down-payment assistance'],
    sourceUrl: 'https://www.toyota.com/centralatlantic/deals-incentives/rav4_apr_f50e0f15-3209-4a71-8286-bb3865fa3359/?vehicles=rav4%2Crav4hybrid%2Crav4prime',
    sourceName: 'Toyota public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'high',
    coverageNote: 'Central Atlantic Toyota lists 4.99% APR for 48 months on the 2026 RAV4, including XLE. Approval, dealer participation, and vehicle availability apply.',
  },
  {
    id: 'offer-elantra-lease-philly-202609',
    vehicleId: 'hyundai-elantra-sel-2026',
    zip: '19104',
    region: 'Philadelphia, PA',
    offerTypes: ['lease'],
    cashAmount: 0,
    aprPercent: null,
    financeTermMonths: null,
    leaseMonthly: 179,
    leaseDueAtSigning: 3999,
    leaseTermMonths: 24,
    expiresAt: '2026-09-30',
    eligibility: ['2026 Elantra SEL Sport FWD', 'Qualified lessees and Hyundai Motor Finance approval required', 'Taxes and fees excluded; confirm mileage allowance and Pennsylvania availability'],
    sourceUrl: 'https://www.hyundaiusa.com/us/en/offers',
    sourceName: 'Hyundai public offers',
    fetchedAt: checkedAt,
    parserConfidence: 'medium',
    coverageNote: 'Hyundai lists $179 per month for 24 months with $3,999 due at signing for the 2026 Elantra SEL Sport FWD. Confirm local terms and inventory with a dealer.',
  },
];

export const sourceStatuses: SourceStatus[] = [
  {
    id: 'nhtsa-vpic',
    name: 'NHTSA vPIC',
    category: 'model-catalog',
    status: 'fixture-backed',
    coverage: 'Checked Sep 28, 2026. vPIC API version 4.06 reports its last code change as Jun 13, 2026. Used for vehicle identity, not incentives.',
    lastChecked: checkedDate,
    url: 'https://vpic.nhtsa.dot.gov/api/',
  },
  {
    id: 'fueleconomy-gov',
    name: 'FuelEconomy.gov',
    category: 'model-catalog',
    status: 'fixture-backed',
    coverage: 'Checked Sep 28, 2026. The official vehicle data page reports an update on Sep 18, 2026; EPA economy data supports fuel-type normalization, not incentives.',
    lastChecked: checkedDate,
    url: 'https://www.fueleconomy.gov/feg/ws/index.shtml',
  },
  {
    id: 'toyota-public-offers',
    name: 'Toyota public offers',
    category: 'oem-offer',
    status: 'fixture-backed',
    coverage: 'Checked Sep 28, 2026. Central Atlantic offers include Pennsylvania and expire Sep 30, 2026. Offers are region-level and remain subject to approval, dealer participation, and inventory. College ($500) and military ($750) rebates are eligibility-limited and are not included in rankings.',
    lastChecked: checkedDate,
    url: 'https://www.toyota.com/centralatlantic/deals-incentives/',
  },
  {
    id: 'ford-public-offers',
    name: 'Ford public offers',
    category: 'oem-offer',
    status: 'adapter-planned',
    coverage: "Checked Sep 28, 2026. The public incentive URL redirected to Ford's vehicle showroom and did not expose verifiable Maverick or Escape APR, lease, rebate, and expiration terms. Those June fixture offers were removed; missing coverage is not proof that no deal exists.",
    lastChecked: checkedDate,
    url: 'https://www.ford.com/incentives/',
  },
  {
    id: 'hyundai-public-offers',
    name: 'Hyundai public offers',
    category: 'oem-offer',
    status: 'fixture-backed',
    coverage: 'Checked Sep 28, 2026. The public page lists current 2026 finance and lease offers. Offers expire Sep 30, 2026; regional eligibility, dealer participation, and combinability need confirmation. Advertised total-savings amounts are unitemized and are not scored as guaranteed rebates.',
    lastChecked: checkedDate,
    url: 'https://www.hyundaiusa.com/us/en/offers',
  },
  {
    id: 'irs-clean-vehicle',
    name: 'IRS clean vehicle credit',
    category: 'tax-credit',
    status: 'historical',
    coverage: 'Checked Sep 28, 2026. The federal new clean vehicle credit is unavailable for vehicles acquired after Sep 30, 2025; no current federal credit is included in these offers.',
    lastChecked: checkedDate,
    url: 'https://www.irs.gov/clean-vehicle-tax-credits',
  },
];
